apiVersion: skaffold/v4beta3
kind: Config

manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: auth
      context: .
      docker:
        dockerfile: auth/Dockerfile
      sync:
        manual:
          - src: auth/src/**/*.ts
            dest: auth/src
          - src: common/src/**/*.ts
            dest: common/src

    - image: tickets
      context: .
      docker:
        dockerfile: tickets/Dockerfile
      sync:
        manual:
          - src: tickets/src/**/*.ts
            dest: tickets/src
          - src: common/src/**/*.ts
            dest: common/src

portForward:
  - resourceType: deployment
    resourceName: auth-depl
    port: 9229
    localPort: 9229

  - resourceType: deployment
    resourceName: tickets-depl
    port: 9230
    localPort: 9230

  - resourceType: deployment
    resourceName: rabbitmq-depl
    port: 15672
    localPort: 15672

  - resourceType: deployment
    resourceName: prometheus-depl
    port: 9090
    localPort: 9090

  - resourceType: deployment
    resourceName: grafana-depl
    port: 3000
    localPort: 3001
